package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'SubProject2_HttpsGithubComKseniailinaMovProject20191git'
in the project with id = 'SubProject2', and delete the patch script.
*/
create(RelativeId("SubProject2"), GitVcsRoot({
    id("SubProject2_HttpsGithubComKseniailinaMovProject20191git")
    name = "https://github.com/kseniailina/MovProject_2019_1.git"
    url = "https://github.com/kseniailina/MovProject_2019_1.git"
    authMethod = password {
        userName = "kseniailina"
        password = "credentialsJSON:a5ae659c-6d5b-4aa8-a98c-6de895ba289e"
    }
}))

